### ISSUE TITLE
How to backtrack the pixel image information?

### ISSUE THREAD

**Issue by jyotiramande** [sunsided/focus-stacking#1]
I want to get information of the pixel (from the fully focused image) that from which input image it was pulled in for the fully focused image. How do I do so?

**Comment by sunsided** [comment]
When synthesizing the image using the index of the highest energy source, store away that index at the according position in a new matrix. That way, you'd build an image as well as a map of pixel coordinate to image index.

Something along the lines of

```python
fused_array = np.zeros(energies_test_1.shape[0:2], dtype=np.float32)
source_map = -np.ones(energies_test_1.shape[0:2], dtype=np.int32) # -1 indicates no mapping

rows, cols = fused_array.shape
for row in range(rows):
    for col in range(cols):
        idx = highest_energies_idx[row, col]
        fused_array[row, col] = source[idx, row, col]
        source_map[row, col] = idx
```

That is, however, basically the same as the "depth from focus" section.
